### ISSUE TITLE
GUI prompting for authentication

### ISSUE THREAD

**Issue by fraschm1998** [grayfallstown/html2maud#3]
I try to run html2maud-bin from cli using `html2maud-bin` and the gui opens and promps for authentication for 127.0.0.1:8080.

![Screenshot_2023-10-20-11-55-46_5378](https://github.com/grayfallstown/html2maud/assets/54919428/a0b0d41e-bdef-469c-9427-383c5f72a2dc)

**Comment by grayfallstown** [comment]
Not sure what is going on there, I have to see when I find time to debug this.
For the time being I would suggest using [the online version](https://grayfallstown.github.io/html2maud/)

**Comment by fraschm1998** [comment]
Sorry it's not actually a bug, I have hydroxide running on port 8080 so instead of connecting to paro it tries to connect to hydroxide which prompts for the login
